### ISSUE TITLE
GithubRepoSearchViewControllerがdeinitされない？

### ISSUE THREAD

**Issue by jormungand2006** [yimajo/VIPERBook1Samples#22]
VIPERの勉強用にVIPER研究読本1を買ってこちらのサンプルも動かしていて気になったのですが、
GithubRepoSearchViewControllerにdeinitを仕込んでも特に呼ばれず、サンプル一覧とSearchを行ったり来たりした分だけ
GithubRepoSearchViewControllerのインスタンスがdebug memory graphに残ってるのが気になりました。

GithubRepoDetailViewControllerの方はdeinit呼ばれてるので違いがあるとしたら、PresenterのDependency辺りかなとは思うんですけど・・
ちなみにXcode 12.2で動かしてます。

<img width="1512" alt="スクリーンショット 2020-12-26 1 42 04" src="https://user-images.githubusercontent.com/6168526/103139056-b0278080-471b-11eb-8182-ba6aa34c5974.png">

**Comment by yimajo** [comment]
@jormungand2006 
すいません、issueに気づけませんでした。

GithubRepoSearchViewControllerが強参照で下記のように循環参照されていたのが原因のようです。

- ViewControllerがPresenterを保持
- PresenterがRouterを保持
- RouterがViewControllerを保持

#23 で対応し強参照しないようにしました（書籍の方もあとから修正します）。
ご連絡ありがとうございました！

**Comment by jormungand2006** [comment]
確かにdeinitされるの確認できましたー
ありがとうございます！

あまり詳しく理解できてないんですが、
Routerを以下に変える事で必要なタイミングで解放してくれる認識で合ってますでしょうか？
weakだとすぐに解放されてしまうのは前に自分で試した時の記憶があります。
unowned var searchViewController: UIViewController

**Comment by yimajo** [comment]
@jormungand2006 
weakだとすぐに解放されてしまうがunownedだからすぐに解放されないということはないはずです。

今回の変更はweakにしても強参照しなくなり循環参照しなくなるためそれでもよかったのですが、weakにするということはRouterがViewControllerを存在しなくてもよいように作ることになり、それはこちらの意図する想定とは違うためです。RouterはViewControllerがかならず存在していると考えて設計をしたほうがシンプルだからです。そう設計する理由は画面遷移を司るRouterが、遷移元のViewControllerを持っていないという前提はありえないと考えるためです（そういう前提は単に設計の話で決めの問題であって、遷移先に遷移するためのRouterが遷移元のViewControllerを持たないという決めで作る人もいるかもしれません）。
